# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterFollower',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(default='0', max_length=50)),
                ('followercount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(default='0', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='twitterfollower',
            name='followed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='app2.TwitterUser'),
        ),
    ]
