# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterfollower',
            name='username',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='username',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
