# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20160425_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.TextField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.TextField(default='0', max_length=10),
        ),
    ]
